version: 2
updates:

  - package-ecosystem: "pip"  # also supports Poetry
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions" # only supports updates using the GitHub repository syntax, such as actions/checkout@v3
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

