[tool.poetry]
name = "spond"
version = "0.10.1"
description = "Simple, unofficial library with some example scripts to access data from the Spond API."
authors = ["Ola Thoresen <ola@nytt.no>"]
license = "GPL 3.0"
readme = 'README.md'
repository = 'https://github.com/Olen/Spond'

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.8.3"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.11.4"  # >= 5.12 requires Python >= 3.8

[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"

[tool.black]
line-length = 88
target-version = ['py37']

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
